In [73]:
import pandas as pd
import numpy as np

In [74]:
df = pd.read_csv("data/Matches.csv")

df.head(-5)

/var/folders/tk/dy9ktf4s05b7lhv4_j0bl_740000gn/T/ipykernel_71123/3158542772.py:1: DtypeWarning: Columns (0: MatchTime) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/Matches.csv")

,Division,MatchDate,MatchTime,HomeTeam,AwayTeam,HomeElo,AwayElo,Form3Home,Form5Home,Form3Away,...,MaxUnder25,HandiSize,HandiHome,HandiAway,C_LTH,C_LTA,C_VHD,C_VAD,C_HTB,C_PHB
0,F1,2000-07-28,NaN,Marseille,Troyes,1686.34,1586.57,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,F1,2000-07-28,NaN,Paris SG,Strasbourg,1714.89,1642.51,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,F2,2000-07-28,NaN,Wasquehal,Nancy,1465.08,1633.80,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,F1,2000-07-29,NaN,Auxerre,Sedan,1635.58,1624.22,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,F1,2000-07-29,NaN,Bordeaux,Metz,1734.34,1673.11,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230547,T1,2025-06-01,17:00:00,Bodrumspor,Besiktas,1345.44,1494.38,3.0,3.0,4.0,...,2.20,0.8,1.78,2.03,0.3863,0.2599,0.0100,0.1794,0.0303,0.1341
230548,T1,2025-06-01,17:00:00,Samsunspor,Kayserispor,1431.06,1394.59,7.0,10.0,4.0,...,2.45,-0.8,1.95,1.85,0.0195,0.0407,0.2005,0.0137,0.7156,0.0100
230549,SP2,2025-06-01,17:30:00,Levante,Eibar,1605.75,1529.63,9.0,10.0,9.0,...,2.38,-1.0,1.88,1.93,0.4790,0.0252,0.1071,0.0487,0.3176,0.0224
230550,SP2,2025-06-01,17:30:00,Santander,Granada,1527.51,1537.00,2.0,5.0,6.0,...,2.43,0.0,1.98,1.83,0.0489,0.4992,0.0617,0.0119,0.0566,0.3218
230551,SP2,2025-06-01,17:30:00,Huesca,Eldense,1496.86,1423.86,3.0,4.0,5.0,...,1.74,-0.3,1.80,2.00,0.4442,0.1408,0.1621,0.0312,0.1971,0.0246

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 230557 entries, 0 to 230556
Data columns (total 48 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Division     230557 non-null  str
 1   MatchDate    230557 non-null  str
 2   MatchTime    99072 non-null   str
 3   HomeTeam     230557 non-null  str
 4   AwayTeam     230557 non-null  str
 5   HomeElo      141597 non-null  float64
 6   AwayElo      141528 non-null  float64
 7   Form3Home    229057 non-null  float64
 8   Form5Home    229057 non-null  float64
 9   Form3Away    229057 non-null  float64
 10  Form5Away    229057 non-null  float64
 11  FTHome       230554 non-null  float64
 12  FTAway       230554 non-null  float64
 13  FTResult     230554 non-null  str
 14  HTHome       175977 non-null  float64
 15  HTAway       175977 non-null  float64
 16  HTResult     175977 non-null  str
 17  HomeShots    114735 non-null  float64
 18  AwayShots    114738 non-null  float64
 19  HomeTarget   113929 non-null  float64
 20  AwayTarget   113932 non-null  float64
 21  HomeFouls    113973 non-null  float64
 22  AwayFouls    113973 non-null  float64
 23  HomeCorners  114363 non-null  float64
 24  AwayCorners  114363 non-null  float64
 25  HomeYellow   119298 non-null  float64
 26  AwayYellow   119299 non-null  float64
 27  HomeRed      119299 non-null  float64
 28  AwayRed      119297 non-null  float64
 29  OddHome      227527 non-null  float64
 30  OddDraw      227527 non-null  float64
 31  OddAway      227527 non-null  float64
 32  MaxHome      202922 non-null  float64
 33  MaxDraw      202922 non-null  float64
 34  MaxAway      202922 non-null  float64
 35  Over25       148398 non-null  float64
 36  Under25      148397 non-null  float64
 37  MaxOver25    148398 non-null  float64
 38  MaxUnder25   148397 non-null  float64
 39  HandiSize    156733 non-null  float64
 40  HandiHome    156475 non-null  float64
 41  HandiAway    156451 non-null  float64
 42  C_LTH        112602 non-null  float64
 43  C_LTA        112602 non-null  float64
 44  C_VHD        112602 non-null  float64
 45  C_VAD        112602 non-null  float64
 46  C_HTB        112602 non-null  float64
 47  C_PHB        112602 non-null  float64
dtypes: float64(41), str(7)
memory usage: 84.4 MB

In [76]:
df.shape

(230557, 48)

In [77]:
df = df[df["MatchDate"] > '2020-1-1']
df.shape

(56161, 48)

In [78]:
df["Division"].value_counts()

Division
E1     2722
E3     2722
E2     2721
SP2    2281
EC     2267
ARG    2211
USA    2046
I2     1890
I1     1880
E0     1872
SP1    1870
T1     1806
F2     1774
F1     1701
BRA    1658
P1     1513
D2     1512
D1     1512
N1     1504
B1     1479
JAP    1436
MEX    1354
ROM    1324
POL    1213
SC0    1060
CHN     988
SWE     981
RUS     975
NOR     975
SC1     834
SC3     819
SC2     814
SUI     805
DEN     804
AUT     803
IRL     731
FIN     684
G1      620
Name: count, dtype: int64

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56161 entries, 174396 to 230556
Data columns (total 48 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Division     56161 non-null  str
 1   MatchDate    56161 non-null  str
 2   MatchTime    56161 non-null  str
 3   HomeTeam     56161 non-null  str
 4   AwayTeam     56161 non-null  str
 5   HomeElo      30461 non-null  float64
 6   AwayElo      30456 non-null  float64
 7   Form3Home    56161 non-null  float64
 8   Form5Home    56161 non-null  float64
 9   Form3Away    56161 non-null  float64
 10  Form5Away    56161 non-null  float64
 11  FTHome       56161 non-null  float64
 12  FTAway       56161 non-null  float64
 13  FTResult     56161 non-null  str
 14  HTHome       37135 non-null  float64
 15  HTAway       37135 non-null  float64
 16  HTResult     37135 non-null  str
 17  HomeShots    34866 non-null  float64
 18  AwayShots    34866 non-null  float64
 19  HomeTarget   34866 non-null  float64
 20  AwayTarget   34866 non-null  float64
 21  HomeFouls    34864 non-null  float64
 22  AwayFouls    34864 non-null  float64
 23  HomeCorners  34866 non-null  float64
 24  AwayCorners  34866 non-null  float64
 25  HomeYellow   37135 non-null  float64
 26  AwayYellow   37135 non-null  float64
 27  HomeRed      37135 non-null  float64
 28  AwayRed      37135 non-null  float64
 29  OddHome      56119 non-null  float64
 30  OddDraw      56119 non-null  float64
 31  OddAway      56119 non-null  float64
 32  MaxHome      56119 non-null  float64
 33  MaxDraw      56119 non-null  float64
 34  MaxAway      56119 non-null  float64
 35  Over25       37135 non-null  float64
 36  Under25      37135 non-null  float64
 37  MaxOver25    37135 non-null  float64
 38  MaxUnder25   37135 non-null  float64
 39  HandiSize    37116 non-null  float64
 40  HandiHome    36901 non-null  float64
 41  HandiAway    36900 non-null  float64
 42  C_LTH        34853 non-null  float64
 43  C_LTA        34853 non-null  float64
 44  C_VHD        34853 non-null  float64
 45  C_VAD        34853 non-null  float64
 46  C_HTB        34853 non-null  float64
 47  C_PHB        34853 non-null  float64
dtypes: float64(41), str(7)
memory usage: 20.6 MB

In [80]:
df.columns = df.columns.str.lower().str.strip().str.replace(" ", "")
df.columns

Index(['division', 'matchdate', 'matchtime', 'hometeam', 'awayteam', 'homeelo',
       'awayelo', 'form3home', 'form5home', 'form3away', 'form5away', 'fthome',
       'ftaway', 'ftresult', 'hthome', 'htaway', 'htresult', 'homeshots',
       'awayshots', 'hometarget', 'awaytarget', 'homefouls', 'awayfouls',
       'homecorners', 'awaycorners', 'homeyellow', 'awayyellow', 'homered',
       'awayred', 'oddhome', 'odddraw', 'oddaway', 'maxhome', 'maxdraw',
       'maxaway', 'over25', 'under25', 'maxover25', 'maxunder25', 'handisize',
       'handihome', 'handiaway', 'c_lth', 'c_lta', 'c_vhd', 'c_vad', 'c_htb',
       'c_phb'],
      dtype='str')

In [81]:
df["matchdate"] = pd.to_datetime(df["matchdate"])
df = df.drop(columns=["matchtime"])
df.head()

,division,matchdate,hometeam,awayteam,homeelo,awayelo,form3home,form5home,form3away,form5away,...,maxunder25,handisize,handihome,handiaway,c_lth,c_lta,c_vhd,c_vad,c_htb,c_phb
174396,SP1,2020-10-01,Ath Bilbao,Cadiz,1722.75,1559.02,3.0,6.0,3.0,3.0,...,1.58,-0.8,1.72,2.07,0.0491,0.4974,0.2742,0.0099,0.0358,0.1336
174397,SP1,2020-10-01,Sevilla,Levante,1867.56,1707.61,7.0,13.0,6.0,9.0,...,2.27,-1.3,2.04,1.86,0.0514,0.1748,0.0099,0.6257,0.0195,0.1186
174398,SP1,2020-10-01,Celta,Barcelona,1682.95,1960.98,5.0,6.0,6.0,12.0,...,2.46,1.0,1.99,1.91,0.1274,0.2928,0.0105,0.0860,0.0503,0.4331
174399,MEX,2020-10-02,Queretaro,Club America,NaN,NaN,1.0,3.0,5.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174400,ARG,2020-10-02,Union de Santa Fe,River Plate,NaN,NaN,3.0,4.0,7.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
df = df.drop(columns=["form3home", "form3away"])

In [83]:
df[
    ((df["fthome"] > df["ftaway"]) & (df["ftresult"] != "H")) |
    ((df["fthome"] < df["ftaway"]) & (df["ftresult"] != "A")) |
    ((df["fthome"] == df["ftaway"]) & (df["ftresult"] != "D"))
]
mismatches = (
    ((df["fthome"] > df["ftaway"]) & (df["ftresult"] != "H")) |
    ((df["fthome"] < df["ftaway"]) & (df["ftresult"] != "A")) |
    ((df["fthome"] == df["ftaway"]) & (df["ftresult"] != "D"))
)

mismatches.sum()

np.int64(0)

In [84]:
df[
    ((df["hthome"] > df["htaway"]) & (df["htresult"] != "H")) |
    ((df["hthome"] < df["htaway"]) & (df["htresult"] != "A")) |
    ((df["hthome"] == df["htaway"]) & (df["htresult"] != "D"))
]
mismatches = (
    ((df["hthome"] > df["htaway"]) & (df["htresult"] != "H")) |
    ((df["hthome"] < df["htaway"]) & (df["htresult"] != "A")) |
    ((df["hthome"] == df["htaway"]) & (df["htresult"] != "D"))
)

mismatches.sum()

np.int64(0)

In [85]:
df["ftresult"] = (df["ftresult"] == "H").astype(int)
df["htresult"] = (df["htresult"] == "H").astype(int)

In [86]:
print(df[df["homeshots"] < 0]["homeshots"].value_counts())
print(df[df["awayshots"] < 0]["awayshots"].value_counts())

Series([], Name: count, dtype: int64)
Series([], Name: count, dtype: int64)

In [87]:
p_draw = 1 / df["odddraw"]
p_away = 1 / df["oddaway"]

df["oddwin"] = df["oddhome"]
df["oddloss"] = 1 / (p_draw + p_away)

p_draw = 1 / df["maxdraw"]
p_away = 1 / df["maxaway"]

df["maxwin"] = df["maxhome"]
df["maxloss"] = 1 / (p_draw + p_away)

df = df.drop(columns=["oddhome","odddraw","oddaway","maxhome","maxdraw","maxaway"])

In [88]:
df.columns

Index(['division', 'matchdate', 'hometeam', 'awayteam', 'homeelo', 'awayelo',
       'form5home', 'form5away', 'fthome', 'ftaway', 'ftresult', 'hthome',
       'htaway', 'htresult', 'homeshots', 'awayshots', 'hometarget',
       'awaytarget', 'homefouls', 'awayfouls', 'homecorners', 'awaycorners',
       'homeyellow', 'awayyellow', 'homered', 'awayred', 'over25', 'under25',
       'maxover25', 'maxunder25', 'handisize', 'handihome', 'handiaway',
       'c_lth', 'c_lta', 'c_vhd', 'c_vad', 'c_htb', 'c_phb', 'oddwin',
       'oddloss', 'maxwin', 'maxloss'],
      dtype='str')

In [89]:
df = df.drop(columns=['c_lth', 'c_lta', 'c_vhd', 'c_vad', 'c_htb', 'c_phb'])

In [90]:
df.columns

Index(['division', 'matchdate', 'hometeam', 'awayteam', 'homeelo', 'awayelo',
       'form5home', 'form5away', 'fthome', 'ftaway', 'ftresult', 'hthome',
       'htaway', 'htresult', 'homeshots', 'awayshots', 'hometarget',
       'awaytarget', 'homefouls', 'awayfouls', 'homecorners', 'awaycorners',
       'homeyellow', 'awayyellow', 'homered', 'awayred', 'over25', 'under25',
       'maxover25', 'maxunder25', 'handisize', 'handihome', 'handiaway',
       'oddwin', 'oddloss', 'maxwin', 'maxloss'],
      dtype='str')

In [91]:
print(df["homeelo"].isnull().sum())
print(df["awayelo"].isnull().sum())

25700
25705

In [92]:
print("both null ->", (df["homeelo"].isnull() & df["awayelo"].isnull()).sum())
df[(df["homeelo"].isnull() & df["awayelo"].isnull())]

both null -> 23289

,division,matchdate,hometeam,awayteam,homeelo,awayelo,form5home,form5away,fthome,ftaway,...,under25,maxover25,maxunder25,handisize,handihome,handiaway,oddwin,oddloss,maxwin,maxloss
174399,MEX,2020-10-02,Queretaro,Club America,NaN,NaN,3.0,11.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.41,1.511236,2.62,1.621538
174400,ARG,2020-10-02,Union de Santa Fe,River Plate,NaN,NaN,4.0,8.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.86,1.112098,6.90,1.173754
174401,MEX,2020-10-02,Juarez,Necaxa,NaN,NaN,4.0,5.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2.18,1.617311,2.32,1.737410
174402,ROM,2020-10-02,FC Botosani,FC Hermannstadt,NaN,NaN,7.0,8.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.57,2.253251,1.65,2.440301
174405,ROM,2020-10-02,FCSB,Academica Clinceni,NaN,NaN,12.0,5.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.19,4.242457,1.24,5.204082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230104,SC3,2025-05-03,East Fife,Elgin,NaN,NaN,9.0,9.0,2.0,0.0,...,1.96,1.84,2.05,-0.5,1.88,1.98,1.86,1.825363,1.92,1.908497
230105,SC3,2025-05-03,Forfar,Stirling,NaN,NaN,6.0,9.0,0.0,0.0,...,2.03,1.75,2.05,-1.0,1.93,1.93,1.50,2.383119,1.53,2.533302
230106,SC3,2025-05-03,Spartans,Edinburgh City,NaN,NaN,6.0,7.0,3.0,1.0,...,1.88,1.93,1.93,-0.3,1.83,1.98,2.08,1.646859,2.15,1.711679
230107,SC3,2025-05-03,Stranraer,Bonnyrigg Rose,NaN,NaN,3.0,6.0,0.0,1.0,...,1.88,1.93,1.93,0.3,1.80,2.05,2.81,1.370546,2.88,1.413118
230456,G1,2025-05-18,Volos NFC,Athens Kallithea,NaN,NaN,12.0,5.0,0.0,2.0,...,1.76,2.05,1.79,-0.3,1.80,2.00,2.06,1.712496,2.10,1.792469

In [93]:
teams = pd.concat([
    df[["hometeam", "homeelo"]].rename(columns={"hometeam":"team", "homeelo":"elo"}),
    df[["awayteam", "awayelo"]].rename(columns={"awayteam":"team", "awayelo":"elo"})
])

teams["is_null"] = teams["elo"].isnull()

summary = teams.groupby("team")["is_null"].value_counts().unstack(fill_value=0)
summary.columns = ["non_null", "null"]
summary.sort_values("null", ascending=False)

             non_null  null
team
Doncaster           0   227
Stevenage           0   227
Burton              0   227
Bristol Rvs         0   227
Carlisle            0   227
...               ...   ...
Chelsea           187     0
Millwall          227     0
Milan             188     0
Midtjylland       136     0
Zwolle            133     0

[881 rows x 2 columns]

In [94]:
null_rows = df[df["homeelo"].isnull() | df["awayelo"].isnull()]
pd.concat([null_rows["division"]]).value_counts()

division
E3     2722
E2     2687
EC     2267
ARG    2211
USA    2046
BRA    1658
JAP    1436
MEX    1354
ROM    1275
POL    1050
CHN     988
RUS     902
SC1     830
SC3     819
SC2     814
SUI     805
IRL     731
SWE     721
FIN     682
AUT     595
NOR     369
T1      357
DEN     341
G1      184
SP2      84
P1       68
B1       63
I2       38
D2       17
E0        2
Name: count, dtype: int64

In [104]:
teams = pd.concat([
    df[["hometeam", "homeelo"]].rename(columns={"hometeam":"team","homeelo":"elo"}),
    df[["awayteam", "awayelo"]].rename(columns={"awayteam":"team","awayelo":"elo"})
])

team_mean = teams.groupby("team")["elo"].mean()
global_mean = teams["elo"].mean()

In [105]:
df["homeelo"] = df["homeelo"].fillna(
    df["hometeam"].map(team_mean)
)

df["homeelo"] = df["homeelo"].fillna(global_mean)

df["awayelo"] = df["awayelo"].fillna(
    df["awayteam"].map(team_mean)
)

df["awayelo"] = df["awayelo"].fillna(global_mean)

In [106]:
print(df["homeelo"].isnull().sum())
print(df["awayelo"].isnull().sum())

0
0

In [107]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56161 entries, 174396 to 230556
Data columns (total 37 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   division     56161 non-null  str
 1   matchdate    56161 non-null  datetime64[us]
 2   hometeam     56161 non-null  str
 3   awayteam     56161 non-null  str
 4   homeelo      56161 non-null  float64
 5   awayelo      56161 non-null  float64
 6   form5home    56161 non-null  float64
 7   form5away    56161 non-null  float64
 8   fthome       56161 non-null  float64
 9   ftaway       56161 non-null  float64
 10  ftresult     56161 non-null  int64
 11  hthome       37135 non-null  float64
 12  htaway       37135 non-null  float64
 13  htresult     56161 non-null  int64
 14  homeshots    34866 non-null  float64
 15  awayshots    34866 non-null  float64
 16  hometarget   34866 non-null  float64
 17  awaytarget   34866 non-null  float64
 18  homefouls    34864 non-null  float64
 19  awayfouls    34864 non-null  float64
 20  homecorners  34866 non-null  float64
 21  awaycorners  34866 non-null  float64
 22  homeyellow   37135 non-null  float64
 23  awayyellow   37135 non-null  float64
 24  homered      37135 non-null  float64
 25  awayred      37135 non-null  float64
 26  over25       37135 non-null  float64
 27  under25      37135 non-null  float64
 28  maxover25    37135 non-null  float64
 29  maxunder25   37135 non-null  float64
 30  handisize    37116 non-null  float64
 31  handihome    36901 non-null  float64
 32  handiaway    36900 non-null  float64
 33  oddwin       56119 non-null  float64
 34  oddloss      56119 non-null  float64
 35  maxwin       56119 non-null  float64
 36  maxloss      56119 non-null  float64
dtypes: datetime64[us](1), float64(31), int64(2), str(3)
memory usage: 15.9 MB

In [108]:
features = [
    ("homeshots",   "hometeam"),
    ("awayshots",   "awayteam"),
    ("hometarget",  "hometeam"),
    ("awaytarget",  "awayteam"),
    ("homefouls",   "hometeam"),
    ("awayfouls",   "awayteam"),
    ("homecorners", "hometeam"),
    ("awaycorners", "awayteam")
]

for col, team_col in features:
    team_mean = df.groupby(team_col)[col].mean()
    global_mean = df[col].mean()
    
    df[col] = df[col].fillna(df[team_col].map(team_mean))
    df[col] = df[col].fillna(global_mean)

features = [
    ("homeyellow",  "hometeam"),
    ("awayyellow",  "awayteam"),
    ("homered",     "hometeam"),
    ("awayred",     "awayteam")
]

for col, team_col in features:
    team_median = df.groupby(team_col)[col].median()
    global_median = df[col].median()
    
    df[col] = df[col].fillna(df[team_col].map(team_median))
    df[col] = df[col].fillna(global_median)

In [109]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56161 entries, 174396 to 230556
Data columns (total 37 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   division     56161 non-null  str
 1   matchdate    56161 non-null  datetime64[us]
 2   hometeam     56161 non-null  str
 3   awayteam     56161 non-null  str
 4   homeelo      56161 non-null  float64
 5   awayelo      56161 non-null  float64
 6   form5home    56161 non-null  float64
 7   form5away    56161 non-null  float64
 8   fthome       56161 non-null  float64
 9   ftaway       56161 non-null  float64
 10  ftresult     56161 non-null  int64
 11  hthome       37135 non-null  float64
 12  htaway       37135 non-null  float64
 13  htresult     56161 non-null  int64
 14  homeshots    56161 non-null  float64
 15  awayshots    56161 non-null  float64
 16  hometarget   56161 non-null  float64
 17  awaytarget   56161 non-null  float64
 18  homefouls    56161 non-null  float64
 19  awayfouls    56161 non-null  float64
 20  homecorners  56161 non-null  float64
 21  awaycorners  56161 non-null  float64
 22  homeyellow   56161 non-null  float64
 23  awayyellow   56161 non-null  float64
 24  homered      56161 non-null  float64
 25  awayred      56161 non-null  float64
 26  over25       37135 non-null  float64
 27  under25      37135 non-null  float64
 28  maxover25    37135 non-null  float64
 29  maxunder25   37135 non-null  float64
 30  handisize    37116 non-null  float64
 31  handihome    36901 non-null  float64
 32  handiaway    36900 non-null  float64
 33  oddwin       56119 non-null  float64
 34  oddloss      56119 non-null  float64
 35  maxwin       56119 non-null  float64
 36  maxloss      56119 non-null  float64
dtypes: datetime64[us](1), float64(31), int64(2), str(3)
memory usage: 15.9 MB

In [ ]:
df["season"] = df["matchdate"].dt.year.where(
    df["matchdate"].dt.month >= 7,
    df["matchdate"].dt.year - 1
)

cols = [
    "over25",
    "under25",
    "maxover25",
    "maxunder25",
    "handisize",
    "handihome",
    "handiaway"
]

for col in cols:
    
    group_median = df.groupby(["division","season"])[col].transform("median")
    
    df[col] = df[col].fillna(group_median)
    df[col] = df[col].fillna(df[col].median())

In [113]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56161 entries, 174396 to 230556
Data columns (total 38 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   division     56161 non-null  str
 1   matchdate    56161 non-null  datetime64[us]
 2   hometeam     56161 non-null  str
 3   awayteam     56161 non-null  str
 4   homeelo      56161 non-null  float64
 5   awayelo      56161 non-null  float64
 6   form5home    56161 non-null  float64
 7   form5away    56161 non-null  float64
 8   fthome       56161 non-null  float64
 9   ftaway       56161 non-null  float64
 10  ftresult     56161 non-null  int64
 11  hthome       37135 non-null  float64
 12  htaway       37135 non-null  float64
 13  htresult     56161 non-null  int64
 14  homeshots    56161 non-null  float64
 15  awayshots    56161 non-null  float64
 16  hometarget   56161 non-null  float64
 17  awaytarget   56161 non-null  float64
 18  homefouls    56161 non-null  float64
 19  awayfouls    56161 non-null  float64
 20  homecorners  56161 non-null  float64
 21  awaycorners  56161 non-null  float64
 22  homeyellow   56161 non-null  float64
 23  awayyellow   56161 non-null  float64
 24  homered      56161 non-null  float64
 25  awayred      56161 non-null  float64
 26  over25       56161 non-null  float64
 27  under25      56161 non-null  float64
 28  maxover25    56161 non-null  float64
 29  maxunder25   56161 non-null  float64
 30  handisize    56161 non-null  float64
 31  handihome    56161 non-null  float64
 32  handiaway    56161 non-null  float64
 33  oddwin       56119 non-null  float64
 34  oddloss      56119 non-null  float64
 35  maxwin       56119 non-null  float64
 36  maxloss      56119 non-null  float64
 37  season       56161 non-null  int32
dtypes: datetime64[us](1), float64(31), int32(1), int64(2), str(3)
memory usage: 16.1 MB

In [114]:
df['htresult'].value_counts()

htresult
0    43804
1    12357
Name: count, dtype: int64

In [115]:
df["hthome"].value_counts()

hthome
0.0    19281
1.0    12631
2.0     4094
3.0      911
4.0      184
5.0       32
6.0        2
Name: count, dtype: int64

In [116]:
df["htaway"].value_counts()

htaway
0.0    21883
1.0    11392
2.0     3153
3.0      599
4.0       92
5.0       14
7.0        1
6.0        1
Name: count, dtype: int64

In [117]:
df["hthome"] = df["hthome"].fillna(df["htresult"])
df["htaway"] = df["htaway"].fillna(1 - df["htresult"])

In [118]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56161 entries, 174396 to 230556
Data columns (total 38 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   division     56161 non-null  str
 1   matchdate    56161 non-null  datetime64[us]
 2   hometeam     56161 non-null  str
 3   awayteam     56161 non-null  str
 4   homeelo      56161 non-null  float64
 5   awayelo      56161 non-null  float64
 6   form5home    56161 non-null  float64
 7   form5away    56161 non-null  float64
 8   fthome       56161 non-null  float64
 9   ftaway       56161 non-null  float64
 10  ftresult     56161 non-null  int64
 11  hthome       56161 non-null  float64
 12  htaway       56161 non-null  float64
 13  htresult     56161 non-null  int64
 14  homeshots    56161 non-null  float64
 15  awayshots    56161 non-null  float64
 16  hometarget   56161 non-null  float64
 17  awaytarget   56161 non-null  float64
 18  homefouls    56161 non-null  float64
 19  awayfouls    56161 non-null  float64
 20  homecorners  56161 non-null  float64
 21  awaycorners  56161 non-null  float64
 22  homeyellow   56161 non-null  float64
 23  awayyellow   56161 non-null  float64
 24  homered      56161 non-null  float64
 25  awayred      56161 non-null  float64
 26  over25       56161 non-null  float64
 27  under25      56161 non-null  float64
 28  maxover25    56161 non-null  float64
 29  maxunder25   56161 non-null  float64
 30  handisize    56161 non-null  float64
 31  handihome    56161 non-null  float64
 32  handiaway    56161 non-null  float64
 33  oddwin       56119 non-null  float64
 34  oddloss      56119 non-null  float64
 35  maxwin       56119 non-null  float64
 36  maxloss      56119 non-null  float64
 37  season       56161 non-null  int32
dtypes: datetime64[us](1), float64(31), int32(1), int64(2), str(3)
memory usage: 16.1 MB